### ISSUE TITLE
prefix links with https

### ISSUE THREAD

**Issue by leobalter** [jquery/qunitjs.com#109]
Based on a [feedback](https://twitter.com/antumbral/status/666735928761712644), we should replace our links to set a protocol prefix (`https:`) rather than just calling them from `//`.

It's a better approach if the examples are copied to a local environment and opened via a file protocol.

**Comment by arthurvr** [comment]
:+1:. Besides from the reason mentioned there, nowadays `https://` is fast and increasingly necessary, so protocol-relative URLs are really becoming an anti-pattern.
