### ISSUE TITLE
Assert: "throws" removed signature (block, string, string) not in migration guide despite reference to migration guide in exception message

### ISSUE THREAD

**Issue by platinumazure** [jquery/qunitjs.com#122]
The "throws" assertion throws an exception when given (block, string, string) arguments. It mentions the migration guide, but the migration guide does not contain information about this at all.

**Comment by platinumazure** [comment]
I'm happy to draft a PR for this in the next couple of weeks if needed. If I do, though, I would appreciate a link to any content writing/style guides you may have that I should look at. Thanks!

**Comment by jzaefferer** [comment]
There's http://contribute.jquery.org/style-guide/prose/

Otherwise you'd have to look at existing documents for references.

**Comment by platinumazure** [comment]
@jzaefferer Thanks, that helped a lot. Opened PR #123.
