### ISSUE TITLE
Wrong "Latest version of qunit."

### ISSUE THREAD

**Issue by najela** [jquery/qunitjs.com#98]
As of https://github.com/jquery/qunitjs.com/commit/91afca0f08eff337a452b259de21404cafd59b29, The latest version of qunit is 1.18.1. Both at http://code.jquery.com/qunit/ and https://qunitjs.com/, the latest version is still stated as 1.18.0.

**Comment by jzaefferer** [comment]
You're mistaking a version of the qunitjs.com website repo with the version of the QUnit library itself. The website tracks the major and minor, but not the patch version of the library. 1.18.0 is indeed the latest release of QUnit.

**Comment by najela** [comment]
Well this was false alarm.  Its the website http://qunitjs.com/ which is at version 1.18.1. The library itself is still at version [1.18.0](https://github.com/jquery/qunit/releases)

**Comment by najela** [comment]
@jzaefferer Thanks for the clarification
